[package]
name = "rusted"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
fake = "2.8.0"
quickcheck = "1.0.3"
regex = "1.8.1"
